# Generated by Django 3.2.13 on 2023-12-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coffee_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='좋아하는 커피타입'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='temp@email.com', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=11, null=True, verbose_name='휴대폰번호'),
        ),
    ]
